package:
  name: bankid-service-fake
  version: 0.1.0
  description: BankID web service fake intended for use during relying party testing
  target-architecture:
    - all
  copyright:
    - license: MIT
      paths:
        - '*'
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - nodejs
      - npm

pipeline:
  - name: Build
    runs: |
      APPDIR="${{targets.destdir}}/usr/share/webapps/${{package.name}}"
      mkdir -p "${APPDIR}"
      cp package.json package-lock.json "${APPDIR}"
      cp -r source "${APPDIR}"
      cd "${APPDIR}"
      npm install --omit=dev
