name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # Required for keyless signing with fulcio
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Run Melange
        uses: chainguard-dev/actions/melange-build@main
        with:
          config: melange.yaml
          sign-with-temporary-key: true
          repository-append: packages
          # Tempprarily build only amd64
          archs: amd64

      - name: Debug
        run: 'tree -a'

      - name: Run apko publish
        uses: chainguard-images/actions/apko-publish@main
        # Don't publish pull request builds
        if: ${{ github.event_name != 'pull_request' }}
        id: apko-publish
        with:
          config: apko.yaml
          tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
          keyring-append: /github/workspace/melange.rsa.pub
          image_refs: apko.images
          # Tempprarily build only amd64
          archs: amd64

      - name: Sign the image
        # Don't publish pull request builds
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: 'true'
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.apko-publish.outputs.digest }}
